# Generated by Django 4.0.4 on 2022-04-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_productname_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productname',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
